const columns = [
  {
    name: "Security Name",
    dataField: "overrideInstrumentDetail.securityName",
    type: "text",
    width: "min-w-[10rem] max-w-[10rem]",
  },
  {
    name: "ISIN",
    dataField: "overrideInstrumentDetail.isin",
    width: "w-[7.5rem] min-w-[7.5rem]",
    type: "text",
  },
  {
    name: "Status",
    dataField: "overrideStatus",
    type: "text",
    width: "w-20",
  },
  {
    name: "Ticker",
    dataField: "overrideInstrumentDetail.ticker",
    width: "w-20",
    type: "text",
  },
  {
    name: "Exchange",
    dataField: "overrideInstrumentDetail.exchange",
    type: "text",
    width: "min-w-[10rem] max-w-[10rem]",
  },
  {
    name: "Security Type",
    dataField: "overrideInstrumentDetail.securityType",
    type: "text",
    width: "w-28",
  },
  {
    name: "LTV at IM",
    dataField: "",
    width: "w-28",
    type: "text",
  },
  {
    name: "LTV Override (%)",
    dataField: "ltvOverrideValue",
    width: "w-20",
    type: "text",
  },
  {
    name: "LTV Override Note",
    dataField: "ltvOverrideNote",
    type: "text",
    width: "min-w-[10rem]",
  },
  {
    name: "Creator",
    dataField: "createdByUser",
    width: "w-24",
    type: "text",
  },
  {
    name: "Creation Date",
    dataField: "createdAt",
    width: "w-28",
    type: "date",
  },
  {
    name: "Valid From",
    dataField: "startDate",
    width: "w-28",
    type: "date",
  },
  {
    name: "Valid To",
    dataField: "endDate",
    width: "w-28",
    type: "date",
  },
  {
    name: "Last Modified",
    dataField: "modifiedAt",
    width: "w-28",
    type: "date",
  },
];

const searchColumn = [
  {
    name: "Security Name",
    dataField: "ltvResponse.securityName",
    type: "text",
    width: "min-w-[10rem]",
  },
  {
    name: "ISIN",
    dataField: "ltvResponse.isin",
    width: "w-24",
    type: "text",
    alignment: "text-left",
  },
  {
    name: "Ticker",
    dataField: "ltvResponse.ticker",
    width: "w-20",
    type: "text",
    alignment: "text-center",
  },
  {
    name: "Exchange",
    dataField: "ltvResponse.exchange",
    type: "text",
    width: "min-w-[10rem]",
  },
  {
    name: "Security Type",
    dataField: "ltvResponse.securityType",
    type: "text",
    width: "w-28",
  },
  {
    name: "Last Close Price",
    dataField: "ltvResponse.marketData.pxLast",
    type: "text",
    width: "w-28",
  },
  {
    name: "Currency",
    dataField: "ltvResponse.marketData.crncy",
    type: "text",
    width: "w-28",
  },
  {
    name: "LTV at IM",
    dataField: "ltvResponse.ltvCalculation.ltvAtIm",
    width: "w-28",
    type: "text",
  },
  {
    name: "Quantity",
    dataField: "ltvResponse.marketData.volumeAvg3m",
    width: "w-28",
    type: "text",
  },
  {
    name: "MV (USD)",
    dataField: "ltvResponse.ltvCalculation.mv",
    width: "w-20",
    alignment: "text-center",
    type: "text",
  },
  {
    name: "CV (USD)",
    dataField: "ltvResponse.ltvCalculation.cv",
    width: "w-20",
    alignment: "text-center",
    type: "text",
  },
  {
    name: "Conc.",
    dataField: "overrideInstrumentDetail.conc",
    width: "w-24",
    type: "text",
  },
  {
    name: "LP",
    dataField: "ltvResponse.ltvCalculation.lp",
    width: "w-28",
    type: "text",
  },
  {
    name: "Disclaimer",
    dataField: "ltvResponse.ltvCalculation.disclaimer",
    width: "w-28",
    type: "text",
    alignment: "text-center",
  },
];

export { columns, searchColumn };
